name: context merge

on:
  push:
    branches:
      - main 
    path: src/

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: 3.12
    - name: dir to json
      run: python3 ./context-merge.py

    - name: Commit and Push to build Branch
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add context.json
        git commit -m "Update Context JSON"
        git push origin main
