name: Setup React Scaffold

on:
  workflow_dispatch:

jobs:
  setup_scaffold:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # 选择你需要的Node.js版本

    - name: Install Create React App globally
      run: npm install -g create-react-app

    - name: Create React App
      run: create-react-app my-react-app

    - name: Push Scaffold to Repository
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'
        git add my-react-app/ # Add the React app files excluding node_modules
        git commit -m "Initial React app scaffold by GitHub Actions" || echo "No changes to commit"
        git push origin HEAD:main # Ensure you're pushing to the correct branch

